-- MySQL Script generated by MySQL Workbench
-- 11/07/16 18:23:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `ID` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `access level` INT NOT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `year` INT NOT NULL,
  `major` VARCHAR(45) NOT NULL,
  `minor` VARCHAR(45) NOT NULL,
  `department_abbreviation` VARCHAR(10) NOT NULL,
  `user_email1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_email1`),
  INDEX `fk_student_user1_idx` (`user_email1` ASC),
  UNIQUE INDEX `user_email1_UNIQUE` (`user_email1` ASC),
  CONSTRAINT `fk_student_user1`
    FOREIGN KEY (`user_email1`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`department` ;

CREATE TABLE IF NOT EXISTS `mydb`.`department` (
  `abbreviation` VARCHAR(10) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`abbreviation`),
  UNIQUE INDEX `abbreviation_UNIQUE` (`abbreviation` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`section`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`section` ;

CREATE TABLE IF NOT EXISTS `mydb`.`section` (
  `title` VARCHAR(45) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` TIME NULL,
  `course_abbr` VARCHAR(45) NOT NULL,
  `days` VARCHAR(5) NOT NULL,
  `term` VARCHAR(7) NOT NULL,
  `year` INT NOT NULL,
  `credits` INT NOT NULL,
  `instructor` VARCHAR(45) NULL,
  `room` VARCHAR(10) NULL,
  `department_abbreviation` VARCHAR(10) NOT NULL,
  `endtime` TIME NULL,
  PRIMARY KEY (`id`, `year`, `term`),
  INDEX `fk_Section_department1_idx` (`department_abbreviation` ASC),
  CONSTRAINT `fk_Section_department1`
    FOREIGN KEY (`department_abbreviation`)
    REFERENCES `mydb`.`department` (`abbreviation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`schedule` ;

CREATE TABLE IF NOT EXISTS `mydb`.`schedule` (
  `Schedule ID` INT NOT NULL AUTO_INCREMENT,
  `Schedule Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Schedule ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_has_schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`student_has_schedule` ;

CREATE TABLE IF NOT EXISTS `mydb`.`student_has_schedule` (
  `student_user_email1` VARCHAR(45) NOT NULL,
  `schedule_Schedule ID` INT NOT NULL,
  PRIMARY KEY (`student_user_email1`, `schedule_Schedule ID`),
  INDEX `fk_student_has_schedule_schedule1_idx` (`schedule_Schedule ID` ASC),
  INDEX `fk_student_has_schedule_student1_idx` (`student_user_email1` ASC),
  CONSTRAINT `fk_student_has_schedule_student1`
    FOREIGN KEY (`student_user_email1`)
    REFERENCES `mydb`.`student` (`user_email1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_schedule_schedule1`
    FOREIGN KEY (`schedule_Schedule ID`)
    REFERENCES `mydb`.`schedule` (`Schedule ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`schedule_has_section`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`schedule_has_section` ;

CREATE TABLE IF NOT EXISTS `mydb`.`schedule_has_section` (
  `schedule_Schedule ID` INT NOT NULL,
  `section_id` INT NOT NULL,
  `section_year` INT NOT NULL,
  `section_term` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`schedule_Schedule ID`, `section_id`, `section_year`, `section_term`),
  INDEX `fk_schedule_has_section_section1_idx` (`section_id` ASC, `section_year` ASC, `section_term` ASC),
  INDEX `fk_schedule_has_section_schedule1_idx` (`schedule_Schedule ID` ASC),
  CONSTRAINT `fk_schedule_has_section_schedule1`
    FOREIGN KEY (`schedule_Schedule ID`)
    REFERENCES `mydb`.`schedule` (`Schedule ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedule_has_section_section1`
    FOREIGN KEY (`section_id` , `section_year` , `section_term`)
    REFERENCES `mydb`.`section` (`id` , `year` , `term`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
ALTER TABLE mydb.schedule MODIFY `Schedule ID` INT(11) NOT NULL AUTO_INCREMENT;
CREATE UNIQUE INDEX section_id_uindex ON mydb.section (id);
ALTER TABLE mydb.section MODIFY id INT(11) NOT NULL AUTO_INCREMENT;
CREATE UNIQUE INDEX user_ID_uindex ON mydb.user (ID);
ALTER TABLE mydb.user MODIFY ID INT(11) NOT NULL AUTO_INCREMENT;